name: Build Pipeline

on:
  push:
    branches:
      - 'SCRUM-5-as-a-user-i-want-to-login-to-the-system-so-that-i-can-securely-access-my-account'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Display Build Message
        run: echo "GitHub Actions Build Successful"